[package]
name = "fizzbuzz"
version = "0.1.0"
authors = ["takao-h <hayashi_takao@cyberbuzz.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kagura = "0.3.3"
wasm-bindgen = "0.2"
